const skills = [
    {name: "Accounting", base: 5},
    {name: "Anthropology", base:1},
    {name: "Appraise", base:5},
    {name: "Archaelogy", base:1},
    {name: "Charm", base:15},
    {name: "Climb", base:20},
    {name: "Computer Use", base:5},
    {name: "Credit Rating", base:0},
    {name: "Cthulhu Mythos", base:0},
    {name: "Disguise", base:0},
    {name: "Dodge", base:0},
    {name: "Drive", base:20},
    {name: "Electric Repair", base:10},
    {name: "Electronics", base:1},
    {name: "Fast Talk", base:5},
    {name: "Fighting (Brawl)", base:25},
    {name: "Firearms (Handgun)", base:20},
    {name: "Firearms (Rifle/Shotgun)", base:25},
    {name: "First Aid", base:30},
    {name: "History", base:5},
    {name: "Intimidate", base:15},
    {name: "Jump", base:20},
    {name: "Language", base:1},
    {name: "Law", base:5},
    {name: "Library Use", base:20},
    {name: "Listen", base:20},
    {name: "Locksmith", base:1},
    {name: "Mech. Repair", base:10},
    {name: "Medicine", base:1},
    {name: "Natural World", base:10},
    {name: "Navigate", base:10},
    {name: "Occult", base:5},
    {name: "Persuade", base:1},
    {name: "Pilot", base:1},
    {name: "Psychoanalysis", base:1},
    {name: "Psychology", base:10},
    {name: "Ride", base:5},
    {name: "Science", base:1},
    {name: "Sleight of Hand", base:10},
    {name: "Spot Hidden", base:25},
    {name: "Stealth", base:20},
    {name: "Survival", base:10},
    {name: "Swim", base:20},
    {name: "Throw", base:20},
    {name: "Track", base:10},
]

const skillList = [
    "Accounting",
    "Animal Handling",
    "Anthropology",
    "Appraise",
    "Archaeology",
    "Arts and Crafts",
    "Artillery",
    "Charm",
    "Climb",
    "Credit Rating",
    "Cthulhu Mythos",
    "Demolitions",
    "Disguise",
    "Diving",
    "Dodge",
    "Drive Auto",
    "Electrical Repair",
    "Fast Talk",
    "Fighting",
    "Firearms",
    "First Aid",
    "History",
    "Hypnosis",
    "Intimidate",
    "Jump",
    "Language (Others)",
    "Language (Own)",
    "Law",
    "Library Use",
    "Listen",
    "Locksmith",
    "Lore",
    "Mechanical Repair",
    "Medicine",
    "Natural World",
    "Navigate",
    "Occult",
    "Operate Heavy Machinery",
    "Persuade",
    "Science: Pharmacy",
    "Arts and Crafts: Photography",
    "Science: Physics",
    "Pilot",
    "Psychoanalysis",
    "Psychology",
    "Read Lips",
    "Ride",
    "Firearms: Rifle",
    "Science",
    "Firearms: Shotgun",
    "Sleight of Hand",
    "Fighting: Spear",
    "Spot Hidden",
    "Stealth",
    "Firearms: Submachine Gun",
    "Survival",
    "Fighting: Sword",
    "Swim",
    "Throw",
    "Track",
    "Fighting: Whip",
    "Science: Zoology",
    "Arts and Crafts: Acting",
    "Science: Astronomy",
    "Fighting: Axe",
    "Science: Biology",
    "Science: Botany",
    "Firearms: Bow",
    "Fighting: Brawl",
    "Fighting: Chainsaw",
    "Science: Chemistry",
    "Science: Cryptography",
    "Science: Engineering",
    "Arts and Crafts: Fine Art",
    "Fighting: Flail",
    "Firearms: Flamethrower",
    "Science: Forensics",
    "Arts and Crafts: Forgery",
    "Fighting: Garrote",
    "Science: Geology",
    "Firearms: Handgun",
    "Firearms: Heavy Weapons",
    "Firearms: Machine Gun",
    "Science: Mathematics",
    "Science: Meteorology",
    "MODERN ONLY: Computer Use",
    "MODERN ONLY: Electronics"
  ]