export const defaultSkills = [
  { type: "Accounting", subtypes: [], base: 5 },
  { type: "Art and Craft", subtypes: [{ name: "Acting", base: 5 }, { name: "Fine Art", base: 5 }, { name: "Photography", base: 5 }, { name: "Forgery", base: 5 }], base: 5 },
  { type: "Animal Handling", subtypes: [], base: 5 },
  { type: "Anthropology", subtypes: [], base: 1 },
  { type: "Appraise", subtypes: [], base: 5 },
  { type: "Archaelogy", subtypes: [], base: 1 },
  { type: "Artillery", subtypes: [], base: 1 },
  { type: "Astronomy", subtypes: [], base: 1 },
  { type: "Charm", subtypes: [], base: 15 },
  { type: "Climb", subtypes: [], base: 20 },
  { type: "Computer Use", subtypes: [], base: 5 ,modern: true},
  { type: "Credit Rating", subtypes: [], base: 0 },
  { type: "Cthulhu Mythos", subtypes: [], base: 0 },
  { type: "Demolitions", subtypes: [], base: 1 },
  { type: "Diving", subtypes: [], base: 1 },
  { type: "Disguise", subtypes: [], base: 0 },
  { type: "Dodge", subtypes: [], base: 0 },
  { type: "Drive", subtypes: [], base: 20 },
  { type: "Electric Repair", subtypes: [], base: 10 },
  { type: "Electronics", subtypes: [], base: 1,modern: true },
  { type: "Fast Talk", subtypes: [], base: 5 },
  { type: "Fighting", subtypes: [{ name: "Axe", base: 15 }, { name: "Brawl", base: 25 }, { name: "Flail", base: 10 }, { name: "Chainsaw", base: 10 }, { name: "Garrote", base: 15 }, { name: "Spear", base: 20 }, { name: "Sword", base: 20 }, { name: "Whip", base: 5 }], base: 25 },
  { type: "Firearms", subtypes: [{ name: "Bow", base: 15 }, { name: "Flamethrower", base: 10 }, { name: "Handgun", base: 20 }, { name: "Heavy Weapons", base: 10 }, { name: "Machine Gun", base: 10 }, { name: "Rifle", base: 25 }, { name: "Submachine Gun", base: 15 }], base: 20 },
  { type: "First Aid", subtypes: [], base: 30 },
  { type: "History", subtypes: [], base: 5 },
  { type: "Hypnosis", subtypes: [], base: 1 },
  { type: "Intimidate", subtypes: [], base: 15 },
  { type: "Jump", subtypes: [], base: 20 },
  { type: "Language", subtypes: [], base: 1 },
  { type: "Law", subtypes: [], base: 5 },
  { type: "Library Use", subtypes: [], base: 20 },
  { type: "Listen", subtypes: [], base: 20 },
  { type: "Locksmith", subtypes: [], base: 1 },
  { type: "Lore", subtypes: [], base: 1 },
  { type: "Mechanical Repair", subtypes: [], base: 10 },
  { type: "Medicine", subtypes: [], base: 1 },
  { type: "Natural World", subtypes: [], base: 10 },
  { type: "Navigate", subtypes: [], base: 10 },
  { type: "Operate Heavy Machinery", subtypes: [], base: 1 },
  { type: "Occult", subtypes: [], base: 5 },
  { type: "Persuade", subtypes: [], base: 1 },
  { type: "Pilot", subtypes: [], base: 1 },
  { type: "Psychoanalysis", subtypes: [], base: 1 },
  { type: "Psychology", subtypes: [], base: 10 },
  { type: "Read Lips", subtypes: [], base: 1 },
  { type: "Ride", subtypes: [], base: 5 },
  { type: "Science", subtypes: [{ name: "Astronomy", base: 1 }, { name: "Biology", base: 1 }, { name: "Botany", base: 1 }, { name: "Chemistry", base: 1 }, { name: "Cryptography", base: 1 }, { name: "Engineering", base: 1 }, { name: "Forensics", base: 1 }, { name: "Geology", base: 1 }, { name: "Mathematics", base: 10 }, { name: "Meteorology", base: 1 }, { name: "Pharmacy", base: 1 }, { name: "Physics", base: 1 }, { name: "Physics", base: 1 }], base: 1 },
  { type: "Sleight of Hand", subtypes: [], base: 10 },
  { type: "Spot Hidden", subtypes: [], base: 25 },
  { type: "Stealth", subtypes: [], base: 20 },
  { type: "Survival", subtypes: [], base: 10 },
  { type: "Swim", subtypes: [], base: 20 },
  { type: "Throw", subtypes: [ { name: "Spear",base: 20 },], base: 20 },
  { type: "Track", subtypes: [], base: 10 },
];

export const list_of_skills = [
  "Accounting",
  "Animal Handling",
  "Anthropology",
  "Appraise",
  "Archaeology",
  "Arts and Crafts",
  "Artillery",
  "Charm",
  "Climb",
  "Credit Rating",
  "Cthulhu Mythos",
  "Demolitions",
  "Disguise",
  "Diving",
  "Dodge",
  "Drive Auto",
  "Electrical Repair",
  "Fast Talk",
  "Fighting",
  "Firearms",
  "First Aid",
  "History",
  "Hypnosis",
  "Intimidate",
  "Jump",
  "Language (Others)",
  "Language (Own)",
  "Law",
  "Library Use",
  "Listen",
  "Locksmith",
  "Lore",
  "Mechanical Repair",
  "Medicine",
  "Natural World",
  "Navigate",
  "Occult",
  "Operate Heavy Machinery",
  "Persuade",
  "Science: Pharmacy",
  "Arts and Crafts: Photography",
  "Science: Physics",
  "Pilot",
  "Psychoanalysis",
  "Psychology",
  "Read Lips",
  "Ride",
  "Firearms: Rifle",
  "Science",
  "Firearms: Shotgun",
  "Sleight of Hand",
  "Fighting: Spear",
  "Spot Hidden",
  "Stealth",
  "Firearms: Submachine Gun",
  "Survival",
  "Fighting: Sword",
  "Swim",
  "Throw",
  "Track",
  "Fighting: Whip",
  "Science: Zoology",
  "Arts and Crafts: Acting",
  "Science: Astronomy",
  "Fighting: Axe",
  "Science: Biology",
  "Science: Botany",
  "Firearms: Bow",
  "Fighting: Brawl",
  "Fighting: Chainsaw",
  "Science: Chemistry",
  "Science: Cryptography",
  "Science: Engineering",
  "Arts and Crafts: Fine Art",
  "Fighting: Flail",
  "Firearms: Flamethrower",
  "Science: Forensics",
  "Arts and Crafts: Forgery",
  "Fighting: Garrote",
  "Science: Geology",
  "Firearms: Handgun",
  "Firearms: Heavy Weapons",
  "Firearms: Machine Gun",
  "Science: Mathematics",
  "Science: Meteorology",
  "MODERN ONLY: Computer Use",
  "MODERN ONLY: Electronics",
] as const;
