export const API_URL: { [key: string]: string } = {
  development: "http://localhost:5000",
  production: "https://dungeon-bot-server.herokuapp.com",
};

export const list_of_skills = [
  "Accounting",
  "Animal Handling",
  "Anthropology",
  "Appraise",
  "Archaeology",
  "Arts and Crafts",
  "Artillery",
  "Charm",
  "Climb",
  "Credit Rating",
  "Cthulhu Mythos",
  "Demolitions",
  "Disguise",
  "Diving",
  "Dodge",
  "Drive Auto",
  "Electrical Repair",
  "Fast Talk",
  "Fighting",
  "Firearms",
  "First Aid",
  "History",
  "Hypnosis",
  "Intimidate",
  "Jump",
  "Language (Others)",
  "Language (Own)",
  "Law",
  "Library Use",
  "Listen",
  "Locksmith",
  "Lore",
  "Mechanical Repair",
  "Medicine",
  "Natural World",
  "Navigate",
  "Occult",
  "Operate Heavy Machinery",
  "Persuade",
  "Science: Pharmacy",
  "Arts and Crafts: Photography",
  "Science: Physics",
  "Pilot",
  "Psychoanalysis",
  "Psychology",
  "Read Lips",
  "Ride",
  "Firearms: Rifle",
  "Science",
  "Firearms: Shotgun",
  "Sleight of Hand",
  "Fighting: Spear",
  "Spot Hidden",
  "Stealth",
  "Firearms: Submachine Gun",
  "Survival",
  "Fighting: Sword",
  "Swim",
  "Throw",
  "Track",
  "Fighting: Whip",
  "Science: Zoology",
  "Arts and Crafts: Acting",
  "Science: Astronomy",
  "Fighting: Axe",
  "Science: Biology",
  "Science: Botany",
  "Firearms: Bow",
  "Fighting: Brawl",
  "Fighting: Chainsaw",
  "Science: Chemistry",
  "Science: Cryptography",
  "Science: Engineering",
  "Arts and Crafts: Fine Art",
  "Fighting: Flail",
  "Firearms: Flamethrower",
  "Science: Forensics",
  "Arts and Crafts: Forgery",
  "Fighting: Garrote",
  "Science: Geology",
  "Firearms: Handgun",
  "Firearms: Heavy Weapons",
  "Firearms: Machine Gun",
  "Science: Mathematics",
  "Science: Meteorology",
  "MODERN ONLY: Computer Use",
  "MODERN ONLY: Electronics",
] as const;
